spring.application.name=spring_boot_hw_003
#spring.datasource.url=jdbc:postgresql://localhost:5432/event_tracking_system
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.deserialization.fail-on-unknown-properties=true
spring.datasource.url=jdbc:postgresql://db.lmyqolwejnqgnyeouvaw.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Sethadmin@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# ? REQUIRED for Supabase
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
