spring.application.name=spring_boot_hw_003

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jackson.deserialization.fail-on-unknown-properties=true

#  Neon Database Connection
spring.datasource.url=jdbc:postgresql://ep-twilight-truth-akwgue6z-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pakH5M8OZcbF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=org.eventtracking.spring_boot_hw_003.model